name: Run Cypress with Cucumber

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_STANDARD_USER: ${{ secrets.CYPRESS_STANDARD_USER }}
          CYPRESS_STANDARD_PASS: ${{ secrets.CYPRESS_STANDARD_PASS }}
